version: '3.7'
volumes:
    dados:
services: 
    db: 
        image: postgres:9.6     
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=db
        volumes:
            # Volume dos dados
            - dados:/var/lib/postgresql/data
            # Scripts
            - ./scripts:/scripts    
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    frontend: 
        image: nginx:1.16
        volumes:
            # Site
            - ./web:/usr/share/nginx/html/
        ports:
            - 80:80
    app:
        image: python:3.6
        volumes:
            # Aplicação
            - ./app:/app
        working_dir: /app
        command: ./app.sh
        ports: 
            - 8080:8080    
