version: '3.7'
volumes:
    dados:
services: 
    db: 
        image: postgres:9.6     
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=db
        volumes:
            # Volume dos dados
            - dados:/var/lib/postgresql/data
            # Scripts
            - ./scripts:/scripts    
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql